# Site settings
title: Remarks from DIY projects 
email: peter.vojtek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  DIY, the Maker Movement, Quantified Self, Arduino, Wiring 
baseurl: "/diy" # the subpath of your site, e.g. /blog/
url: "https://petervojtek.github.io" # the base hostname & protocol for your site
github_username: petervojtek
comments: true
paginate: 10
paginate_path: "/:num"

# Build settings
markdown: kramdown
